[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"
  included_files = ["*.py", "requirements.txt"]
  node_bundler = "esbuild"

[functions.search]
  handler = "search.handler"
  timeout = "3"  # 设置超时时间为3秒

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' https://*.netlify.app/.netlify/functions/* https://suggestion.baidu.com/*;"
    Cache-Control = "public, max-age=60"