[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["cheerio"]

[functions.search]
  handler = "search.handler"
  timeout = "10"  # 恢复默认超时时间

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' https://*.netlify.app/.netlify/functions/* https://www.bing.com https://search.yahoo.com https://www.zhihu.com;"
    Cache-Control = "public, max-age=60"