[build]
  command = ""
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["requests"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200