[build]
  publish = "public"
  functions = "netlify/functions"
  command = "python -m pip install --upgrade pip && pip install -r netlify/functions/requirements.txt --no-deps"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.zhihu_search]
  handler = "zhihu_search.handler"
  runtime = "python3.9"
  timeout = "30"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' https://*.netlify.app/.netlify/functions/* https://www.bing.com https://search.yahoo.com https://www.zhihu.com;"
    Cache-Control = "public, max-age=60"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"