[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  # 设置Python版本
  PYTHON_VERSION = "3.9"
  # ScrapeOps API密钥 (需要在Netlify界面设置)
  SCRAPEOPS_API_KEY = ""

[functions]
  # 设置函数目录
  directory = "netlify/functions"
  # 设置包含的文件
  included_files = ["*.py", "requirements.txt"]
  # 设置处理器
  external_node_modules = []
  node_bundler = "esbuild"

[functions.search]
  # search函数的特定配置
  handler = "search.handler"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; connect-src 'self' https://*.netlify.app/.netlify/functions/* https://api.scrapeops.io/*;"